#MQTT配置信息
yac:
  mqtt:
    #MQTT服务地址，端口号默认11883，如果有多个，用逗号隔开
    url: tcp://elephant:1883
    #用户名
    username: admin
    #密码
    password: 123456
    #客户端id(不能重复)
    clientId: yac_id
    #MQTT默认的消息推送主题，实际可在调用接口是指定
    #topic: topic
