server:
  port: 8080
yac:
  influx:
    enabled: false
    readUrl: http://elephant:8086
    writeUrl: http://elephant:8086
    username: admin
    password: cloudansys[admin]
    database: db_yxlinks_dev
