server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#邮件配置样例
  mail:
    host: smtp.163.com
    username: test@163.com
    password: 123456
    port: 25
    properties:
      smtp:
        auth: true
        timeout: 2500
      mail:
        smtp:
          ssl:
            enable: false
